# Generated by Django 5.0.4 on 2024-08-13 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyoAuth', '0002_vendorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.ImageField(upload_to='citizenship')),
                ('citizenship_back', models.ImageField(upload_to='citizenship')),
                ('driving_license', models.ImageField(upload_to='driving_license')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
