# Generated by Django 5.0.4 on 2024-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliyoAuth', '0004_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='pan_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
